In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", 100)

In [5]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [7]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [9]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

pytorch_model.bin: 100%|██████████| 438M/438M [07:20<00:00, 994kB/s]  
sentence_bert_config.json: 100%|██████████| 53.0/53.0 [00:00<?, ?B/s]
special_tokens_map.json: 100%|██████████| 239/239 [00:00<00:00, 116kB/s]
tokenizer.json: 100%|██████████| 466k/466k [00:00<00:00, 801kB/s]
tokenizer_config.json: 100%|██████████| 363/363 [00:00<00:00, 121kB/s]
train_script.py: 100%|██████████| 13.1k/13.1k [00:00<00:00, 25.7MB/s]
vocab.txt: 100%|██████████| 232k/232k [00:00<00:00, 939kB/s]
modules.json: 100%|██████████| 349/349 [00:00<00:00, 229kB/s]


(8, 768)

In [10]:
dim = vectors.shape[1]
dim

768

In [11]:
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002B0EC63F540> >

In [12]:
index.add(vectors)

In [33]:
search_query = "An apple a day keeps the doctor away"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [34]:
vec

array([ 1.77042969e-02,  7.70549402e-02, -1.25192869e-02, -1.39331620e-03,
        5.92102809e-03, -1.42679373e-02, -4.72584143e-02,  3.91951995e-03,
        4.41600867e-02,  3.09807714e-02,  9.15983394e-02,  2.02602837e-02,
       -2.16005333e-02,  1.33208008e-02, -4.14275974e-02,  4.16395180e-02,
        4.37019244e-02,  6.06423244e-03,  2.21781377e-02, -1.94715671e-02,
       -3.44190598e-02,  3.79219539e-02,  5.27902367e-03,  2.22010985e-02,
       -1.11636650e-02, -2.53351182e-02,  7.79388547e-02,  3.47348116e-02,
        1.20056551e-02, -6.52653947e-02, -4.83941026e-02, -3.03445365e-02,
       -6.99562728e-02, -2.53461096e-02,  1.78119137e-06,  1.50222257e-02,
        2.15191580e-02,  2.21124776e-02, -8.38034824e-02,  3.70958517e-03,
       -2.21118238e-02, -8.53062496e-02,  6.44918997e-04,  1.62597895e-02,
       -1.88165586e-02,  3.99218164e-02, -3.13138701e-02,  2.47449856e-02,
       -7.98753928e-03,  6.11144565e-02, -1.47846397e-02,  4.10467474e-05,
        1.20446309e-02,  

we need to convert above vector into 2 dimentions of array. bcoz, this search vector expects 2 dimentional array

In [35]:
import numpy as np
# search vector
svec = np.array(vec).reshape(1, -1)

In [36]:
svec

array([[ 1.77042969e-02,  7.70549402e-02, -1.25192869e-02,
        -1.39331620e-03,  5.92102809e-03, -1.42679373e-02,
        -4.72584143e-02,  3.91951995e-03,  4.41600867e-02,
         3.09807714e-02,  9.15983394e-02,  2.02602837e-02,
        -2.16005333e-02,  1.33208008e-02, -4.14275974e-02,
         4.16395180e-02,  4.37019244e-02,  6.06423244e-03,
         2.21781377e-02, -1.94715671e-02, -3.44190598e-02,
         3.79219539e-02,  5.27902367e-03,  2.22010985e-02,
        -1.11636650e-02, -2.53351182e-02,  7.79388547e-02,
         3.47348116e-02,  1.20056551e-02, -6.52653947e-02,
        -4.83941026e-02, -3.03445365e-02, -6.99562728e-02,
        -2.53461096e-02,  1.78119137e-06,  1.50222257e-02,
         2.15191580e-02,  2.21124776e-02, -8.38034824e-02,
         3.70958517e-03, -2.21118238e-02, -8.53062496e-02,
         6.44918997e-04,  1.62597895e-02, -1.88165586e-02,
         3.99218164e-02, -3.13138701e-02,  2.47449856e-02,
        -7.98753928e-03,  6.11144565e-02, -1.47846397e-0

In [37]:
distances, I = index.search(svec, k=2)
# k: how many vectors do you need (it's like K-Nearest Neighbor (KNN))

In [38]:
I

array([[1, 0]], dtype=int64)

In [39]:
distances

array([[1.3433158, 1.7125275]], dtype=float32)

In [41]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

In [42]:
search_query

'An apple a day keeps the doctor away'

exact word is not present in the vectors. this is not like a keyword search. this is a symentic search which means it is the capturering the meaning of the search query and giving you the similar sentence here