In [1]:
import pandas as pd

pd.set_option("display.max_colwidth", 100)

In [5]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [7]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [9]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

pytorch_model.bin: 100%|██████████| 438M/438M [07:20<00:00, 994kB/s]  
sentence_bert_config.json: 100%|██████████| 53.0/53.0 [00:00<?, ?B/s]
special_tokens_map.json: 100%|██████████| 239/239 [00:00<00:00, 116kB/s]
tokenizer.json: 100%|██████████| 466k/466k [00:00<00:00, 801kB/s]
tokenizer_config.json: 100%|██████████| 363/363 [00:00<00:00, 121kB/s]
train_script.py: 100%|██████████| 13.1k/13.1k [00:00<00:00, 25.7MB/s]
vocab.txt: 100%|██████████| 232k/232k [00:00<00:00, 939kB/s]
modules.json: 100%|██████████| 349/349 [00:00<00:00, 229kB/s]


(8, 768)

In [10]:
dim = vectors.shape[1]
dim

768

In [11]:
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002B0EC63F540> >

In [12]:
index.add(vectors)

In [45]:
# search_query = "I want to buy a polo t-shirt"
# search_query = "An apple a day keeps the doctor away"
search_query = "Looking for places to visit during the holidays"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [46]:
vec

array([-5.69071472e-02, -7.85622094e-03, -5.97459078e-02,  1.70311946e-02,
       -1.56358369e-02, -1.14045367e-02,  1.34392101e-02,  1.58603843e-02,
       -5.63509483e-03, -3.65663916e-02, -2.79400349e-02,  9.15879197e-03,
        6.13885485e-02, -8.18535835e-02, -4.09647310e-03, -4.49633077e-02,
        1.87594984e-02, -2.79247947e-02, -6.87940046e-02, -3.13308053e-02,
       -3.87345180e-02,  2.53377836e-02, -2.10142694e-03,  1.09868003e-02,
        6.78736791e-02, -1.60868317e-02, -5.97489439e-02, -1.26970541e-02,
        3.33299264e-02,  4.20751087e-02, -3.19535173e-02, -2.43929159e-02,
        6.78689918e-03,  2.02426817e-02,  1.25888300e-06,  4.73244078e-02,
        2.17978247e-02, -3.91112827e-02,  3.06510348e-02,  9.65033658e-03,
       -3.92406173e-02, -4.86150458e-02,  4.32002172e-03,  1.74005125e-02,
        2.01662183e-02, -7.81874433e-02, -3.52567504e-03, -2.18736418e-02,
       -3.01541295e-02,  1.45584540e-02,  4.68929205e-03,  1.82228815e-02,
       -6.18819632e-02,  

we need to convert above vector into 2 dimentions of array. bcoz, this search vector expects 2 dimentional array

In [47]:
import numpy as np
# search vector
svec = np.array(vec).reshape(1, -1)

In [48]:
svec

array([[-5.69071472e-02, -7.85622094e-03, -5.97459078e-02,
         1.70311946e-02, -1.56358369e-02, -1.14045367e-02,
         1.34392101e-02,  1.58603843e-02, -5.63509483e-03,
        -3.65663916e-02, -2.79400349e-02,  9.15879197e-03,
         6.13885485e-02, -8.18535835e-02, -4.09647310e-03,
        -4.49633077e-02,  1.87594984e-02, -2.79247947e-02,
        -6.87940046e-02, -3.13308053e-02, -3.87345180e-02,
         2.53377836e-02, -2.10142694e-03,  1.09868003e-02,
         6.78736791e-02, -1.60868317e-02, -5.97489439e-02,
        -1.26970541e-02,  3.33299264e-02,  4.20751087e-02,
        -3.19535173e-02, -2.43929159e-02,  6.78689918e-03,
         2.02426817e-02,  1.25888300e-06,  4.73244078e-02,
         2.17978247e-02, -3.91112827e-02,  3.06510348e-02,
         9.65033658e-03, -3.92406173e-02, -4.86150458e-02,
         4.32002172e-03,  1.74005125e-02,  2.01662183e-02,
        -7.81874433e-02, -3.52567504e-03, -2.18736418e-02,
        -3.01541295e-02,  1.45584540e-02,  4.68929205e-0

In [49]:
distances, I = index.search(svec, k=2)
# k: how many vectors do you need (it's like K-Nearest Neighbor (KNN))

In [50]:
I

array([[6, 7]], dtype=int64)

In [51]:
distances

array([[0.92737263, 1.1601744 ]], dtype=float32)

In [52]:
df.loc[I[0]]

text  \
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
6   Travel  
7   Travel

In [53]:
search_query

'Looking for places to visit during the holidays'

exact word is not present in the vectors. this is not like a keyword search. this is a symentic search which means it is the capturering the meaning of the search query and giving you the similar sentence here